### ISSUE TITLE
Nuxt3 - [Vue warn]: Failed to resolve component

### ISSUE THREAD

**Issue by tol64** [view-design/ViewUIPlus#51]
If you set **ssr: true** mode in **Nuxt 3**, ...
```ts
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  ssr: true,
});
```
... you get the following message in the console. 
```log
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)
    at createComponentInstance (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6952:23)
    at renderComponentVNode (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///home/projects/nuxt-starter-7kmya5/.nuxt/dist/server/server.mjs:3388:31)
    at renderComponentSubTree (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (/home/projects/nuxt-starter-7kmya5/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at default (file:///home/projects/nuxt-starter-7kmya5/.nuxt/dist/server/server.mjs:2658:37)
```
[Playback on Stackblitz >>>](https://stackblitz.com/edit/nuxt-starter-7kmya5?file=plugins/view-ui.client.ts)

//---

How do I get rid of this message?

**Comment by likuner** [comment]
@tol64 you can try it again when our new version be released, it will be soon.

**Comment by tol64** [comment]
> @tol64 you can try it again when our new version be released, it will be soon.

Thank you!
Please add more information to the documentation on how to connect the library to a `Nuxt 3` project.

**Comment by tol64** [comment]
> @tol64 you can try it again when our new version be released, it will be soon.

I updated to version `1.1.0` and the error is still showing up:
```log
[Vue warn]: Failed to resolve component: BackTop
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: Divider
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

**Comment by tol64** [comment]
I updated to version `1.3.0` and the error is still showing up:
```log
Nuxt CLI v3.0.0-rc.3                                                                                                                                                                                                                                              14:27:23
                                                                                                                                                                                                                                                                  14:27:23
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.3:3000/
  > Network:  http://192.168.29.1:3000/
  > Network:  http://192.168.232.1:3000/

i Vite client warmed up in 2586ms                                                                                                                                                                                                                                 14:27:31
i Vite server warmed up in 487ms                                                                                                                                                                                                                                  14:27:35
√ Vite server built in 4302ms                                                                                                                                                                                                                                     14:27:39
√ Nitro built in 577 ms                                                                                                                                                                                                                                     nitro 14:27:39
💻 14:27:40.320 app.vue > onServerPrefetch() >
[Vue warn]: Failed to resolve component: BackTop
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: Divider
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
Have there been any changes to fix this problem?

**Comment by icarusion** [comment]
Please create issue on https://github.com/view-design/view-ui-project-nuxt
